# Site settings
title: Dave's Profile
email: dgapitts@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm learning to use GitHub pages with Wheelhouse.io and Patchwork: very cool Pride meetup up Q42!
baseurl: "/patchwork-gh-pages-24"
url: "http://dgapitts.github.io"
github_username:  dgapitts
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index